# Generated by Django 4.0.5 on 2022-08-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_productcategory_servicescategory_services_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicescategory',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'Service Categories'},
        ),
    ]
