# Generated by Django 4.0.1 on 2022-08-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('category',)},
        ),
    ]
